=== NewcastleRSE/health-literacy-logic-app/problemSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Problem",
    "definitions": {
        "Problem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Section"
                    }
                }
            },
            "required": [
                "icon",
                "id",
                "level",
                "long-title",
                "sections",
                "short-title"
            ],
            "title": "Problem"
        },
        "Section": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SectionContent"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "Section"
        },
        "PurpleContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FluffyContent"
                    }
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "project-email": {
                    "type": "string"
                }
            },
            "required": [
                "content-type"
            ],
            "title": "PurpleContent"
        },
        "FluffyContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ContentContentUnion"
                    }
                },
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                }
            },
            "required": [
                "content",
                "content-type"
            ],
            "title": "FluffyContent"
        },
        "TentacledContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "TentacledContent"
        },
        "SectionContent": {
            "anyOf": [
                {
                    "$ref": "#/definitions/PurpleContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "SectionContent"
        },
        "ContentContentUnion": {
            "anyOf": [
                {
                    "$ref": "#/definitions/TentacledContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ContentContentUnion"
        },
        "ContentType": {
            "type": "string",
            "enum": [
                "list",
                "subsection"
            ],
            "title": "ContentType"
        }
    }
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/youth-health-literacy.json
{
    "id": "youth-health-literacy",
    "short-title": "Youth health literacy",
    "long-title": "Children and young people leaving school with low health literacy",
    "level": "Individual / community ",
    "icon": "classroom, literacy, school, students, education.svg",
    "sections": [
        {
            "short-title": "people-involved",
            "long-title": "Who should be involved?",
            "content-type": "list",
            "content": [
                "Teachers",
                "Schools",
                "Local Councils",
                "Libraries",
                "Parents",
                "Community Centres",
                "Places of Worship",
                "Nurseries",
                "'Hidden' care givers (such as relatives)"
            ]
        },
        {
            "short-title": "causes",
            "long-title": "What are the causes of the problem?",
            "content-type": "list",
            "content": [
                "Poverty",
                "Education system that is not working properly",
                "Teaching curriculum that is too full",
                "Carers that no-one knows about e.g. relatives",
                "lack of teaching about health and illness",
                "Children and young people not feeling part of society"
            ]
        },
        {
            "long-title": "What would help? ",
            "short-title": "help",
            "content-type": "list",
            "content": [
                "Health literacy in teacher training",
                "Health literacy in social work training (see also problem)",
                "Teaching health literacy in schools"
            ]
        },
        {
            "short-title": "actions",
            "long-title": "What actions are involved in doing something about this?",
            "content-type": "list",
            "content": [
                "Staff training courses",
                "Frequency of staff training",
                "Reading groups",
                "Engaging with local councils",
                "Engaging with senior managers in schools",
                "Mapping out children and young peoples' teaching organisations"
            ]
        },
        {
            "short-title": "delivery",
            "long-title": "How will we deliver these actions?",
            "content-type": "list",
            "content": [
                "*Setting up children and young peoples' reading groups",
                "*Training courses online and / or face to face"
            ]
        },
        {
            "short-title": "action-outcome",
            "long-title": "What do we expect to come out of these actions?",
            "content-type": "list",
            "content": [
                "Skills to read for health",
                "Skills to count for health",
                "Skills to manage money",
                "Children and young people having better health and well-being",
                "Children and young people leading healthier lives",
                "Healthier social interactions",
                "Number of staff trained",
                "Systems to map and monitor action plans",
                "understanding levels of need"
            ]
        },
        {
            "short-title": "change-marker",
            "long-title": "How will we know things have changed?",
            "content-type": "list",
            "content": [
                "Reading counting and speaking skills for health will be better",
                "More staff will have been trained",
                "More action plans will be in place in places where children and young people learn"
            ]
        },
        {
            "short-title": "short-term-change",
            "long-title": "What short term changes will we see?",
            "content-type": "list",
            "content": [
                "Mapping out of institutions and places to be trained",
                "Training courses planned",
                "Understanding levels of need"
            ]
        },
        {
            "short-title": "long-term-change",
            "long-title": "What do we think will happen in the longer term (3 years)? For example, increased health literacy, better disease control, improved health",
            "content-type": "list",
            "content": [
                "Improved health literacy in children and young people",
                "Healthier lifestyle - exercise, diet, smoking, alcohol",
                "Increased health and well being",
                "Healthier social interactions",
                "Staff trained in health literacy"
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/different-vocabulary.json
{
    "id": "different-vocabulary",
    "short-title": "Different vocabulary",
    "long-title": "Different systems (like health and social services) use different words for things",
    "level": "system",
    "icon": "alphabet, literacy, letters, language, basics.svg",
    "sections": [
        {
            "short-title": "people-involved",
            "long-title": "Who should be involved?",
            "content-type": "list",
            "content": [
                "People who run the different systems"
            ]
        },
        {
            "short-title": "causes",
            "long-title": "What are the causes of the problem?",
            "content-type": "list",
            "content": [
                "A range of different words used by different people",
                "Systems that do not talk to each other",
                "Systems that are not joined up"
            ]
        },
        {
            "short-title": "help",
            "long-title": "What would help? ",
            "content-type": "list",
            "content": [
                "everyone using the same words",
                "using words that are easy to understand",
                "making sure letters to patients and the public are easy to understand",
                "letting people tell us when words are too complex",
                "systems that can be changed if needed",
                "staff training",
                "good policies",
                "good systems"
            ]
        },
        {
            "short-title": "actions",
            "long-title": "What actions are involved in doing something about this?",
            "content-type": "list",
            "content": [
                "talking with people using services",
                "knowing all the different words and what they mean",
                "agreeing on a common list of words across our region",
                "making sure these words are easy to understand",
                "making sure systems are in place to write information that is easy to understand and use simple words",
                "setting goals for meeting targets",
                "developing a role for facilitators"
            ]
        },
        {
            "short-title": "delivery",
            "long-title": "How will we deliver these actions?",
            "content-type": "list",
            "content": [
                "develop data systems that talk with each other",
                "develop a set of words that everyone agrees on",
                "make sure everyone knows what these words mean",
                "develop online and IT tools",
                "use Artificial Intelligence",
                "training courses on what words to use"
            ]
        },
        {
            "short-title": "action-outcome",
            "long-title": "What do we expect to come out of these actions?",
            "content-type": "list",
            "content": [
                "less use of acronyms",
                "clear languages used across systems",
                "more awareness of health literacy",
                "better understanding between systems",
                "better patient and public understanding of materials",
                "information that is more sensitive to different cultures"
            ]
        },
        {
            "short-title": "change-marker",
            "long-title": "How will we know things have changed?",
            "content-type": "list",
            "content": [
                "feedback from people who use the system",
                "random checks",
                "more different systems involved",
                "more organisations trained",
                "cost savings"
            ]
        },
        {
            "short-title": "short-term-change",
            "long-title": "What short term changes could we see?",
            "content-type": "list",
            "content": [
                "We will have action plans in place",
                "systems will work better for patients",
                "more organisations will be involved",
                "more materials will be re-written",
                "better use of resources"
            ]
        },
        {
            "short-title": "long-term-change",
            "long-title": "What do we think will happen in the longer term (3 years)? For example, increased health literacy, better disease control, improved health",
            "content-type": "list",
            "content": [
                "Information that is easier to understand",
                "systems using the same words as each other",
                "systems that are easier to use"
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}
