=== NewcastleRSE/health-literacy-logic-app/problemSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Problem",
    "definitions": {
        "Problem": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Section"
                    }
                }
            },
            "required": [
                "icon",
                "id",
                "level",
                "long-title",
                "sections",
                "short-title"
            ],
            "title": "Problem"
        },
        "Section": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SectionContent"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "Section"
        },
        "PurpleContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                },
                "content-type": {
                    "type": "string"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FluffyContent"
                    }
                },
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "project-email": {
                    "type": "string"
                }
            },
            "required": [
                "content-type"
            ],
            "title": "PurpleContent"
        },
        "FluffyContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ContentContentUnion"
                    }
                },
                "choice-option": {
                    "type": "string"
                },
                "choice-subtitle": {
                    "type": "string"
                }
            },
            "required": [
                "content",
                "content-type"
            ],
            "title": "FluffyContent"
        },
        "TentacledContent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "short-title": {
                    "type": "string"
                },
                "long-title": {
                    "type": "string"
                },
                "content-type": {
                    "$ref": "#/definitions/ContentType"
                },
                "content": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "content",
                "content-type",
                "long-title",
                "short-title"
            ],
            "title": "TentacledContent"
        },
        "SectionContent": {
            "anyOf": [
                {
                    "$ref": "#/definitions/PurpleContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "SectionContent"
        },
        "ContentContentUnion": {
            "anyOf": [
                {
                    "$ref": "#/definitions/TentacledContent"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ContentContentUnion"
        },
        "ContentType": {
            "type": "string",
            "enum": [
                "list",
                "subsection"
            ],
            "title": "ContentType"
        }
    }
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/health-jargon.json
{
    "id": "health-jargon",
    "short-title": "Health jargon",
    "long-title": "Health information is too hard to read and has too much jargon",
    "level": "Individual / community ",
    "icon": "032-prescription.svg",
    "sections": [
        {
            "short-title": "people-involved",
            "long-title": "Who should be involved?",
            "content-type": "list",
            "content": [
                "People who run the systems",
                "Health organisations",
                "local authorities",
                "Staff at every level",
                "The general public",
                "people who find reading tricky",
                "People who find counting tricky"
            ]
        },
        {
            "short-title": "causes",
            "long-title": "What are the causes of the problem?",
            "content-type": "list",
            "content": [
                "Systems that do not talk to each other",
                "Organisations don't know there is a problem",
                "Staff in organisations don't know there is a problem",
                "Organisations don't have targets",
                "Low staff skills in health literacy",
                "Lack of staff time to rewrite materials",
                "Lack of resources to rewrite materials",
                "Not currently part of the culture of organisations",
                "Organisation systems not fully accessible to staff"
            ]
        },
        {
            "long-title": "What would help? ",
            "short-title": "help",
            "content-type": "list",
            "content": [
                "AI",
                "Online and automated tools to help rewrite documents",
                "Standardised systems",
                "staff training",
                "Good organisation policies",
                "Better data systems to safely store information",
                "Sharing resources",
                "Using pictures, diagrams, videos and animations",
                "standardised information"
            ]
        },
        {
            "short-title": "actions",
            "long-title": "What actions are involved in doing something about this?",
            "content-type": "list",
            "content": [
                "Working with people receiving services",
                "Developing automated systems",
                "making the IT systems easier to use",
                "Rewriting materials so that they are easy to read",
                "Developing regional templates and systems",
                "improving systems to include health literacy",
                "giving staff training in health literacy",
                "Making sure staff are trained often enough",
                "training clinical staff",
                "working with graphic illustrators, film makers and animation makers",
                "Checking how complex materials are now (an audit)"
            ]
        },
        {
            "short-title": "delivery",
            "long-title": "How will we deliver these actions?",
            "content-type": "list",
            "content": [
                "Develop IT tools to aid simplifying health information",
                "Automated systems",
                "applying updates across the system",
                "Authorised training including online and face to face",
                "system improvements",
                "developing online materials",
                "work with people who can develop video and audio alternatives",
                "always explain codes and jargon used in materials"
            ]
        },
        {
            "short-title": "action-outcome",
            "long-title": "What do we expect to come out of these actions?",
            "content-type": "list",
            "content": [
                "Clear language used across systems",
                "health information that is easier to read and use",
                "Health information available in other languages",
                "health information in different formats",
                "Less anxiety for people reading and using information"
            ]
        },
        {
            "short-title": "change-marker",
            "long-title": "How will we know things have changed?",
            "content-type": "list",
            "content": [
                "Increased patient satisfaction",
                "Lower readability levels of documents",
                "Asking patients and the public what they think",
                "Describing what patients and the public think",
                "Higher number of languages in which health information is available",
                "Higher quality of life scores",
                "Higher number and percentage of materials written in clear language",
                "Self-assessment questionnaires filled in by patients, members of the public and staff"
            ]
        },
        {
            "short-title": "short-term-change",
            "long-title": "What short term changes will we see?",
            "content-type": "list",
            "content": [
                "We will be developing action plans",
                "Systems will work better for people",
                "Increased satisfaction with services",
                "Staff will be happier and more engaged",
                "People will have better skills for health",
                "Systems will be easier to navigate",
                "Better information for health",
                "Materials will be easier to use"
            ]
        },
        {
            "short-title": "long-term-change",
            "long-title": "What do we think will happen in the longer term (3 years)? For example, increased health literacy, better disease control, improved health",
            "content-type": "list",
            "content": [
                "Patients happier with services",
                "Better health",
                "Fewer people missing appointments",
                "Materials that are easier to use",
                "Reduced health inequalities",
                "Better use of GP and hospital appointments",
                "Less stress and depression",
                "Improved health literacy of the public",
                "More people completing treatment"
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/teachers-health-literacy.json
{
    "id": "teachers-health-literacy",
    "short-title": "Teachers health literacy",
    "long-title": "Teachers and social workers not trained in health literacy",
    "level": "system",
    "icon": "teacher, school, educator, classroom, instructor.svg",
    "sections": [
        {
            "short-title": "heading",
            "long-title": "What is the level being targeted?",
            "content-type": "section-choice",
            "content": [
                {
                    "choice-option": "Micro-level",
                    "choice-subtitle": "Things that happen between individuals, like one-to-one support or care",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Teachers",
                                "Social workers"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "Macro-level",
                    "choice-subtitle": "Big system-wide things, like national policies or data systems",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "The Teaching Regulation Agency (TRA)",
                                "The Social Work Regulation Authority (Social Work England)"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "There is poor awareness of the need for health literacy in training for teaching and social work professionals"
                            ]
                        },
                        {
                            "short-title": "help",
                            "long-title": "What would help to solve the problem?",
                            "content-type": "list",
                            "content": [
                                "Government guidance for regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "actions",
                            "long-title": "What actions are involved in doing something about this?",
                            "content-type": "list",
                            "content": [
                                "Talking with the government about the problem",
                                "Change in government policy",
                                "Talking with regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Writing policy briefs about the issues",
                                "Meeting with key people (e.g. ministers, civil servants, regulatory bodies)"
                            ]
                        },
                        {
                            "short-title": "action-outcome",
                            "long-title": "What do we expect to come out of these actions?",
                            "content-type": "list",
                            "content": [
                                "Health literacy training will be embedded in teaching and social work professional training"
                            ]
                        },
                        {
                            "short-title": "change-marker",
                            "long-title": "How will we know things have changed?",
                            "content-type": "list",
                            "content": [
                                "Health literacy appears in teaching and social work training"
                            ]
                        },
                        {
                            "short-title": "short-term-change",
                            "long-title": "What will have changed in 1 year?",
                            "content-type": "list",
                            "content": [
                                "Policy brief will be given to ministers"
                            ]
                        },
                        {
                            "short-title": "long-term-change",
                            "long-title": "What will have happened in 3 years?",
                            "content-type": "list",
                            "content": [
                                "More teaching and public health professions will be starting to learn about health literacy as they train"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}

=== NewcastleRSE/health-literacy-logic-app/static/problems/health-professionals-literacy.json
{
    "id": "health-professionals-literacy",
    "short-title": "Health professionals literacy",
    "long-title": "Health and public health professionals are not trained in health literacy",
    "level": "system",
    "icon": "039-medical history.svg",
    "sections": [
        {
            "short-title": "heading",
            "long-title": "What is the level being targeted?",
            "content-type": "section-choice",
            "content": [
                {
                    "choice-option": "Micro-level",
                    "choice-subtitle": "Things that happen between individuals, like one-to-one support or care",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Health professionals",
                                "Patient"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Health professionals do not realise how important health literacy is for patient outcomes"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "Meso-level",
                    "choice-subtitle": "Things that happen in organisations or communities, like teamwork or service coordination",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Training providers",
                                "Universities",
                                "Health professionals"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Training providers and universities do not include health literacy in their curricula for health professionals"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Meeting with key people (e.g. ministers, civil servants, regulatory bodies)"
                            ]
                        }
                    ]
                },
                {
                    "choice-option": "Macro-level",
                    "choice-subtitle": "Big system-wide things, like national policies or data systems",
                    "short-title": "help",
                    "long-title": "What would help?",
                    "content-type": "subsection",
                    "content": [
                        {
                            "short-title": "people-involved",
                            "long-title": "Who should be involved?",
                            "content-type": "list",
                            "content": [
                                "Regulatory bodies like the General Medical Council (GMC) and Nursing and Midwifery Council (NMC)"
                            ]
                        },
                        {
                            "short-title": "causes",
                            "long-title": "What are the causes of the problem?",
                            "content-type": "list",
                            "content": [
                                "Regulatory bodies and national standards do not require health literacy training"
                            ]
                        },
                        {
                            "short-title": "help",
                            "long-title": "What would help to solve the problem?",
                            "content-type": "list",
                            "content": [
                                "Government guidance for regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "actions",
                            "long-title": "What actions are involved in doing something about this?",
                            "content-type": "list",
                            "content": [
                                "Talking with the government about the problem",
                                "Change in government policy",
                                "Talking with regulatory bodies"
                            ]
                        },
                        {
                            "short-title": "delivery",
                            "long-title": "How will we deliver these actions?",
                            "content-type": "list",
                            "content": [
                                "Writing policy briefs"
                            ]
                        },
                        {
                            "short-title": "action-outcome",
                            "long-title": "What do we expect to come out of these actions?",
                            "content-type": "list",
                            "content": [
                                "Health literacy training will be embedded in health and public health professional training"
                            ]
                        },
                        {
                            "short-title": "change-marker",
                            "long-title": "How will we know things have changed?",
                            "content-type": "list",
                            "content": [
                                "Health literacy will appear in health and public health training"
                            ]
                        },
                        {
                            "short-title": "short-term-change",
                            "long-title": "What will have changed in 1 year?",
                            "content-type": "list",
                            "content": [
                                "Policy brief to ministers"
                            ]
                        },
                        {
                            "short-title": "long-term-change",
                            "long-title": "What will have happened in 3 years?",
                            "content-type": "list",
                            "content": [
                                "More health and public health professions will be starting to learn about health literacy as they train"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "short-title": "current-activities",
            "long-title": "What are the current activities in this area?",
            "content-type": "project-list",
            "content": [
                {
                    "short-title": "project-1",
                    "long-title": "Project one!",
                    "content-type": "project",
                    "project-email": "project@email.com"
                },
                {
                    "short-title": "project-2",
                    "long-title": "Project two!",
                    "content-type": "project",
                    "project-email": "project2@email.com"
                }
            ]
        }
    ]
}
